spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star_dabang?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    #    url: jdbc:mysql://172.17.0.2:3306/yslocaldb
    username: root
    password: root
    initialization-mode: never

  session:
    store-type: redis
    redis:
      namespace: star_dabang:session

  redis:
    host: localhost
    #    host: 172.18.0.2
    port: 6379


mybatis:
  mapper-locations: classpath:mybatis-mapper/**/*.xml
  type-aliases-package: dabang.star.cafe.domain

---
spring:
  config:
    activate:
      on-profile: test

mybatis:
  mapper-locations: classpath:mybatis-mapper/**/*.xml
  type-aliases-package: dabang.star.cafe.domain
  type-handlers-package: dabang.star.cafe.utils

