spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:aws.yaml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star_dabang?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    #    url: jdbc:mysql://172.17.0.2:3306/yslocaldb?characterEncoding=utf8
    username: root
    password: root
    initialization-mode: always
    data: classpath:data-dev.sql

  session:
    store-type: redis
    redis:
      namespace: star_dabang:session

  cache:
    type: redis

  cloud:
    gcp:
      credentials:
        location: classpath:gcp-credentials.json
      storage:
        bucket: star-dabang

  redis:
    host: localhost
    #    host: 172.18.0.2
    port: 6379

mybatis:
  mapper-locations: classpath:mybatis-mapper/**/*.xml
  type-aliases-package: dabang.star.cafe.domain, dabang.star.cafe.application.data

logging:
  config: classpath:log4j2.yaml

---
spring:
  config:
    activate:
      on-profile: test
    import: optional:aws.yaml

  session:
    store-type: redis
    redis:
      namespace: star_dabang:session

mybatis:
  mapper-locations: classpath:mybatis-mapper/**/*.xml
  type-aliases-package: dabang.star.cafe.domain, dabang.star.cafe.application.data

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.174.0.10:3306/stardabangdb?characterEncoding=utf8
    username: appuser
    password: apppass
    initialization-mode: never

  session:
    store-type: redis
    redis:
      namespace: star_dabang:session

  cache:
    type: redis

  cloud:
    gcp:
      credentials:
        location: classpath:gcp-credentials.json
      storage:
        bucket: star-dabang

  redis:
    host: localhost
    #    host: 172.18.0.2
    port: 6379

mybatis:
  mapper-locations: classpath:mybatis-mapper/**/*.xml
  type-aliases-package: dabang.star.cafe.domain, dabang.star.cafe.application.data

logging:
  config: classpath:log4j2.yaml