DELETE FROM my_menu;
DELETE FROM office_stock;
DELETE FROM product_option;
DELETE FROM product;
DELETE FROM additional_option;
DELETE FROM product_category;
DELETE FROM manager;
DELETE FROM office;
DELETE FROM member;